### PR TITLE
Add rustfmt as its own check in CI

### PR DESCRIPTION
**Pull request by stanislav-tkach**
As far as I can see, we are not using rustfmt on CI, so there is no reason to install it.

### CODE REVIEW

**Comment by iljakuklic** [comment]
Would it make sense to instead use the `--check` mode of rustfmt to verify formatting as a part of the CI process?

**Comment by stanislav-tkach** [comment]
@iljakuklic Highly agree! I have updated the pull request.

**Comment by iljakuklic** [comment]
Should this be a hard error that blocks the PR? Maybe just some sort of "warning" is good enough. Not sure how to make github CI understand the distinction.

**Comment by muursh** [comment]
@iljakuklic by default it will be a "warning" rather than a blocker. We have requirement rules for the 3 OS builds but that's it. As long as the code builds everywhere in theory anything else can be ignored.

**Comment by muursh** [comment]
@stanislav-tkach renamed the PR to match what it actually does now

**Review by muursh — APPROVED** [review]
I'm happy with this

**Review by TheQuantumPhysicist — APPROVED** [review]
While I'm OK with this, keep in mind that clippy auto fixing ruins formatting. It'll be a little annoying.

**Comment by muursh** [comment]
We can always remove it if it gets too annoying

**Review by iljakuklic — APPROVED** [review]

**Pull request merged**
