### PR TITLE
Appease Clippy's default 7 max function parameters limit

### PR DESCRIPTION
**Pull request by alfiedotwtf**
The current value seems like an arbitrary limit, and I need it increased for a blockprod PR to pass clippy.

### CODE REVIEW

**Review by muursh — APPROVED** [review]

**Comment by TheQuantumPhysicist** [comment]
I wouldn't make this a rule. This isn't the right way to go. Usually this is an exception that we do when we have no choice. It's not something we want to allow by default.

Look at it this way: When a clippy exception is made, it triggers a discussion on whether there's a better way to fix this problem.

**Comment by alfiedotwtf** [comment]
Yep, no problem. I figured that by making this PR, it would start that discussion :)

**Comment by TheQuantumPhysicist** [comment]
You can add that exception for the place where you have that problem. There are directives for single functions.

**Comment by alfiedotwtf** [comment]
Closing this as I'll inline it instead.

**Pull request closed without merging**
