### PR TITLE
NFT Proposal

### PR DESCRIPTION
**Pull request by sinitcin**
### Requirements
Mintlayer has to support the below features to be suitable for use in markets and dApps:

**Mint an NFT**
Issuance of a NFT, usually called mint an NFT. Mint an NFT should provide setting:

- NFT owner
- Metadata
- Media url and hash
- Optional refund period
- Optional payouts
- Optional royalties fees

**Metadata**
Metadata has to include fields:
- Full Name 
- Free-form description
- Ticker or symbol 
- Optional Icon URL
- Optional URL to JSON file that may have more info, OpenSea market required their standard for JSON metadata. 
- URL to associated media, preferably to decentralized, content-addressed storage
- Hash of content 
- Optional time when token was minted
- Optional token expires time
- Optional time when token starts being valid
- Optional refund period

**Refund**
The creators are unable to withdraw the funds till the waiting period has been completed. During this waiting period, the buyer is able to return their NFT to the creator and receive their coins back. Refund may be only at adjustable waiting period. There are projects that were mentioned in ERC-721R:

- Exodia offered a 14-day refund period.
- Curious Addy’s Trading Club offered a 100-day refund period.
- CryptoFighters is offering a 45-day refund period.
 
**Payouts**
A mapping of Destination to the amount each should be paid out, in the event of a token-sale. For example, owner and a marketplace paid out when a NFT sells.

_Note: Near blockchain specified count of maximum payouts, but if it less or equal to 10, it unconditionally accepted._ 

**Royalties fees**
A percentage of coins that receive creators when an NFT sell between other blockchain users. Should be configured in mint transaction.

**Transfer ownership**
An NFT might be transferred through UTXO, but some Non-Fungible Token developers, marketplaces, dApps, or artists may require greater control. This required a uniform interface allowing token owners to approve to transfer specific tokens on the owner's behalf.

**Approval Management**
A system for allowing a set of users to transfer specific Non-Fungible Tokens on behalf of an owner. This is the backbone of all NFT marketplaces.
- Grant other users access to transfer NFTs.
- Check if an user has access to a specific token.
- Revoke a specific user the ability to transfer an NFT.
- Revoke all other users the ability to transfer an NFT.

**Burn**
There is no specific features. It should be done like for other tokens. Also have to be cleaned up storage entities that consist an information about the NFT.

**Enumerate functionality**
This is using in marketplaces. We have to provide possibility to enumerate and request info for each NFT that own an user. 

### TODOs:
- [ ] Is hash for content should be Base64-encoded sha256?
- [ ] We have to decide what the maximum payout count

### CODE REVIEW

**Comment by sinitcin** [comment]
### NOTES ABOUT ETHEREUM 

- ERC-721 defines a minimum interface a smart contract must implement to allow unique tokens to be managed, owned, and traded.
- ERC-721R defines refund mechanism for NFT, refund may be only at adjustable waiting period (not yet in standard).
- EIP-2981: NFT Royalty Standard

**Features**:
- Find owner by token ID
- Count all NFTs assigned to an owner
- Change NFT ownership
- Approval Management — A system for allowing a set of users or contracts to transfer specific Non-Fungible Tokens on behalf of an owner.
- Some contracts provided royalties percentage. Royalties enable you to create a list of users that should get paid when the token is sell in a marketplace. For example, if Anna has 5% of royalties, each time the NFT is sell, Anna should get a 5% of the selling price.
  
**Links**:
    • [Standard ERC 721](https://erc721.org/)
    • [EIP-2981: NFT Royalty Standard](https://eips.ethereum.org/EIPS/eip-2981)
    • [Standard candidate for refund](https://github.com/exo-digital-labs/ERC721R)
    • [Approval example](https://etherscan.io/token/0xE42caD6fC883877A76A26A16ed92444ab177E306#code)
    • [Royalties on OpenZeppelin](https://github.com/vickycj/NFTRoyaltySmartContract/blob/5bde2e6a5418a07ecee758cc7c3d2c3d612e3731/contracts/RoyaltySmartContract.sol)

**Comment by sinitcin** [comment]
### NOTES ABOUT SUBSTRATE
There is no specific standard, I found examples, but all of them primitive. For example:
- Pallet-NFT — defines and implements a simple interface for managing a set of non-fungible tokens (NFTs). Assets have an owner and can be created, destroyed and transferred.

Features:
- Simple enumeration of assets
- Simple transfer
- Simple burn
- Mint that require only hash

Links: 
    • https://github.com/danforbes/pallet-nft

**Comment by TheQuantumPhysicist** [comment]
What about ERC-1155?

**Comment by sinitcin** [comment]
### NOTES ABOUT NEAR
NEP-171 and NEP-177 standards explain the minimum interface required to be implemented for NFT, as well as the expected functionality.

Features:
- Mint an NFT – set NFT owner, token unique id, media URL and royalties fees.
- Transfer that might have approval field.
- Retrieve NFT struct by NFT id. 
- Payout – map of accounts vs coin amounts. When a marketplace sell the NFT, all accounts receive payments, for example a market contract and owner. 
-  Market functions:
        ◦ Get a list of all tokens for the account\contract
        ◦ Get number of tokens owned by a given account
        ◦ Get list of all tokens owned by a given account

Links:
-  https://github.com/near-examples/nft-tutorial
-  https://nomicon.io/Standards/Tokens/NonFungibleToken/

**Comment by sinitcin** [comment]
> What about ERC-1155?

Should we add the multi-token transactions in requirements?

ERC-1155 split to single and batch operations for transfer, burn, approval. Moreover, it might use fungible and none-fungible tokens in batch operations. Also, Items are now stored in a single contract with the minimum possible amount of data needed to distinguish the token from other ones. 

[Link](https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/#recieve_hook)

**Comment by sinitcin** [comment]
Also, in ETH you can change royalties percentage and metadata after deploy, shall we support transactions that allow to update NFT metadata?

**Pull request closed without merging**
