### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by alfiedotwtf**

### CODE REVIEW

**Comment by alfiedotwtf** [comment]
I didn't see the `staging` branch in the `git branch -a` list, hence the change, then while I was there decided to add `cmake`.

**Comment by muursh** [comment]
Ah it's the old way the branches used to work, we plan to revert back to the old staging branch system at some point soon so I'm tempted to leave the docs as outdated as they represent a future goal

**Comment by alfiedotwtf** [comment]
Ok cool, sounds good.

**Comment by stanislav-tkach** [comment]
I have made the same mistake before: https://github.com/mintlayer/mintlayer-core/pull/221. 🙃

**Pull request closed without merging**
